// รายชื่อโปเกม่อนสำหรับพูลประมูล
// - id: ไม่ซ้ำกัน (ใช้เป็น key สำรอง)
// - apiName: ชื่อที่ใช้ค้นจาก PokeAPI  https://pokeapi.co/api/v2/pokemon/<apiName>
// - isMega: true = ร่าง Mega (ใช้กรองแท็บ Mega)
// หมายเหตุ: ร่าง Mega ที่ PokeAPI ไม่มีจริง (เช่น mega-raichu-x) ระบบจะใช้รูปร่างปกติแทนอัตโนมัติ
export const POKEMON_LIST = [
  { id: 1, apiName: "abomasnow", displayName: "Abomasnow", isMega: false },
  { id: 2, apiName: "absol", displayName: "Absol", isMega: false },
  { id: 3, apiName: "aegislash", displayName: "Aegislash", isMega: false },
  { id: 4, apiName: "aerodactyl", displayName: "Aerodactyl", isMega: false },
  { id: 5, apiName: "aggron", displayName: "Aggron", isMega: false },
  { id: 6, apiName: "alakazam", displayName: "Alakazam", isMega: false },
  { id: 7, apiName: "alcremie", displayName: "Alcremie", isMega: false },
  { id: 8, apiName: "altaria", displayName: "Altaria", isMega: false },
  { id: 9, apiName: "ampharos", displayName: "Ampharos", isMega: false },
  { id: 10, apiName: "annihilape", displayName: "Annihilape", isMega: false },
  { id: 11, apiName: "appletun", displayName: "Appletun", isMega: false },
  { id: 12, apiName: "araquanid", displayName: "Araquanid", isMega: false },
  { id: 13, apiName: "arbok", displayName: "Arbok", isMega: false },
  { id: 14, apiName: "arboliva", displayName: "Arboliva", isMega: false },
  { id: 15, apiName: "arcanine", displayName: "Arcanine", isMega: false },
  { id: 16, apiName: "arcanine-hisui", displayName: "Arcanine Hisuian Form", isMega: false },
  { id: 17, apiName: "archaludon", displayName: "Archaludon", isMega: false },
  { id: 18, apiName: "ariados", displayName: "Ariados", isMega: false },
  { id: 19, apiName: "armarouge", displayName: "Armarouge", isMega: false },
  { id: 20, apiName: "aromatisse", displayName: "Aromatisse", isMega: false },
  { id: 21, apiName: "audino", displayName: "Audino", isMega: false },
  { id: 22, apiName: "aurorus", displayName: "Aurorus", isMega: false },
  { id: 23, apiName: "avalugg", displayName: "Avalugg", isMega: false },
  { id: 24, apiName: "azumarill", displayName: "Azumarill", isMega: false },
  { id: 25, apiName: "banette", displayName: "Banette", isMega: false },
  { id: 26, apiName: "barbaracle", displayName: "Barbaracle", isMega: false },
  { id: 27, apiName: "basculegion", displayName: "Basculegion", isMega: false },
  { id: 28, apiName: "basculegion-female", displayName: "Basculegion Female", isMega: false },
  { id: 29, apiName: "bastiodon", displayName: "Bastiodon", isMega: false },
  { id: 30, apiName: "baxcalibur", displayName: "Baxcalibur", isMega: false },
  { id: 31, apiName: "beartic", displayName: "Beartic", isMega: false },
  { id: 32, apiName: "beedrill", displayName: "Beedrill", isMega: false },
  { id: 33, apiName: "bellibolt", displayName: "Bellibolt", isMega: false },
  { id: 34, apiName: "blastoise", displayName: "Blastoise", isMega: false },
  { id: 35, apiName: "blaziken", displayName: "Blaziken", isMega: false },
  { id: 36, apiName: "camerupt", displayName: "Camerupt", isMega: false },
  { id: 37, apiName: "castform", displayName: "Castform", isMega: false },
  { id: 38, apiName: "ceruledge", displayName: "Ceruledge", isMega: false },
  { id: 39, apiName: "chandelure", displayName: "Chandelure", isMega: false },
  { id: 40, apiName: "charizard", displayName: "Charizard", isMega: false },
  { id: 41, apiName: "chesnaught", displayName: "Chesnaught", isMega: false },
  { id: 42, apiName: "chimecho", displayName: "Chimecho", isMega: false },
  { id: 43, apiName: "cinderace", displayName: "Cinderace", isMega: false },
  { id: 44, apiName: "clawitzer", displayName: "Clawitzer", isMega: false },
  { id: 45, apiName: "clefable", displayName: "Clefable", isMega: false },
  { id: 46, apiName: "cofagrigus", displayName: "Cofagrigus", isMega: false },
  { id: 47, apiName: "conkeldurr", displayName: "Conkeldurr", isMega: false },
  { id: 48, apiName: "corviknight", displayName: "Corviknight", isMega: false },
  { id: 49, apiName: "crabominable", displayName: "Crabominable", isMega: false },
  { id: 50, apiName: "decidueye", displayName: "Decidueye", isMega: false },
  { id: 51, apiName: "dedenne", displayName: "Dedenne", isMega: false },
  { id: 52, apiName: "delphox", displayName: "Delphox", isMega: false },
  { id: 53, apiName: "diggersby", displayName: "Diggersby", isMega: false },
  { id: 54, apiName: "ditto", displayName: "Ditto", isMega: false },
  { id: 55, apiName: "dragalge", displayName: "Dragalge", isMega: false },
  { id: 56, apiName: "dragapult", displayName: "Dragapult", isMega: false },
  { id: 57, apiName: "dragonite", displayName: "Dragonite", isMega: false },
  { id: 58, apiName: "drampa", displayName: "Drampa", isMega: false },
  { id: 59, apiName: "eelektross", displayName: "Eelektross", isMega: false },
  { id: 60, apiName: "emboar", displayName: "Emboar", isMega: false },
  { id: 61, apiName: "emolga", displayName: "Emolga", isMega: false },
  { id: 62, apiName: "empoleon", displayName: "Empoleon", isMega: false },
  { id: 63, apiName: "espathra", displayName: "Espathra", isMega: false },
  { id: 64, apiName: "espeon", displayName: "Espeon", isMega: false },
  { id: 65, apiName: "excadrill", displayName: "Excadrill", isMega: false },
  { id: 66, apiName: "falinks", displayName: "Falinks", isMega: false },
  { id: 67, apiName: "rotom-fan", displayName: "Fan Rotom", isMega: false },
  { id: 68, apiName: "farfetchd", displayName: "Farfetch'd", isMega: false },
  { id: 69, apiName: "farigiraf", displayName: "Farigiraf", isMega: false },
  { id: 70, apiName: "feraligatr", displayName: "Feraligatr", isMega: false },
  { id: 71, apiName: "fighting", displayName: "Fighting", isMega: false },
  { id: 72, apiName: "flapple", displayName: "Flapple", isMega: false },
  { id: 73, apiName: "flareon", displayName: "Flareon", isMega: false },
  { id: 74, apiName: "floette", displayName: "Floette", isMega: false },
  { id: 75, apiName: "florges", displayName: "Florges", isMega: false },
  { id: 76, apiName: "forretress", displayName: "Forretress", isMega: false },
  { id: 77, apiName: "froslass", displayName: "Froslass", isMega: false },
  { id: 78, apiName: "rotom-frost", displayName: "Frost Rotom", isMega: false },
  { id: 79, apiName: "furfrou", displayName: "Furfrou", isMega: false },
  { id: 80, apiName: "gallade", displayName: "Gallade", isMega: false },
  { id: 81, apiName: "garbodor", displayName: "Garbodor", isMega: false },
  { id: 82, apiName: "garchomp", displayName: "Garchomp", isMega: false },
  { id: 83, apiName: "gardevoir", displayName: "Gardevoir", isMega: false },
  { id: 84, apiName: "garganacl", displayName: "Garganacl", isMega: false },
  { id: 85, apiName: "gengar", displayName: "Gengar", isMega: false },
  { id: 86, apiName: "gholdengo", displayName: "Gholdengo", isMega: false },
  { id: 87, apiName: "glaceon", displayName: "Glaceon", isMega: false },
  { id: 88, apiName: "glalie", displayName: "Glalie", isMega: false },
  { id: 89, apiName: "glimmora", displayName: "Glimmora", isMega: false },
  { id: 90, apiName: "gliscor", displayName: "Gliscor", isMega: false },
  { id: 91, apiName: "gogoat", displayName: "Gogoat", isMega: false },
  { id: 92, apiName: "golisopod", displayName: "Golisopod", isMega: false },
  { id: 93, apiName: "golurk", displayName: "Golurk", isMega: false },
  { id: 94, apiName: "goodra", displayName: "Goodra", isMega: false },
  { id: 95, apiName: "gourgeist", displayName: "Gourgeist", isMega: false },
  { id: 96, apiName: "grapploct", displayName: "Grapploct", isMega: false },
  { id: 97, apiName: "greninja", displayName: "Greninja", isMega: false },
  { id: 98, apiName: "grimmsnarl", displayName: "Grimmsnarl", isMega: false },
  { id: 99, apiName: "gyarados", displayName: "Gyarados", isMega: false },
  { id: 100, apiName: "hatterene", displayName: "Hatterene", isMega: false },
  { id: 101, apiName: "hawlucha", displayName: "Hawlucha", isMega: false },
  { id: 102, apiName: "rotom-heat", displayName: "Heat Rotom", isMega: false },
  { id: 103, apiName: "heliolisk", displayName: "Heliolisk", isMega: false },
  { id: 104, apiName: "heracross", displayName: "Heracross", isMega: false },
  { id: 105, apiName: "hippowdon", displayName: "Hippowdon", isMega: false },
  { id: 106, apiName: "houndoom", displayName: "Houndoom", isMega: false },
  { id: 107, apiName: "houndstone", displayName: "Houndstone", isMega: false },
  { id: 108, apiName: "hydrapple", displayName: "Hydrapple", isMega: false },
  { id: 109, apiName: "hydreigon", displayName: "Hydreigon", isMega: false },
  { id: 110, apiName: "incineroar", displayName: "Incineroar", isMega: false },
  { id: 111, apiName: "indeedee", displayName: "Indeedee", isMega: false },
  { id: 112, apiName: "indeedee-f", displayName: "Indeedee Female", isMega: false },
  { id: 113, apiName: "infernape", displayName: "Infernape", isMega: false },
  { id: 114, apiName: "inteleon", displayName: "Inteleon", isMega: false },
  { id: 115, apiName: "jolteon", displayName: "Jolteon", isMega: false },
  { id: 116, apiName: "kangaskhan", displayName: "Kangaskhan", isMega: false },
  { id: 117, apiName: "kingambit", displayName: "Kingambit", isMega: false },
  { id: 118, apiName: "kleavor", displayName: "Kleavor", isMega: false },
  { id: 119, apiName: "klefki", displayName: "Klefki", isMega: false },
  { id: 120, apiName: "kommo-o", displayName: "Kommo-o", isMega: false },
  { id: 121, apiName: "krookodile", displayName: "Krookodile", isMega: false },
  { id: 122, apiName: "leafeon", displayName: "Leafeon", isMega: false },
  { id: 123, apiName: "liepard", displayName: "Liepard", isMega: false },
  { id: 124, apiName: "lopunny", displayName: "Lopunny", isMega: false },
  { id: 125, apiName: "lucario", displayName: "Lucario", isMega: false },
  { id: 126, apiName: "luxray", displayName: "Luxray", isMega: false },
  { id: 127, apiName: "lycanroc-dusk", displayName: "Lycanroc Dusk Form", isMega: false },
  { id: 128, apiName: "lycanroc-midday", displayName: "Lycanroc Midday Form", isMega: false },
  { id: 129, apiName: "lycanroc-midnight", displayName: "Lycanroc Midnight Form", isMega: false },
  { id: 130, apiName: "mabosstiff", displayName: "Mabosstiff", isMega: false },
  { id: 131, apiName: "machamp", displayName: "Machamp", isMega: false },
  { id: 132, apiName: "malamar", displayName: "Malamar", isMega: false },
  { id: 133, apiName: "mamoswine", displayName: "Mamoswine", isMega: false },
  { id: 134, apiName: "manectric", displayName: "Manectric", isMega: false },
  { id: 135, apiName: "maushold", displayName: "Maushold", isMega: false },
  { id: 136, apiName: "mawile", displayName: "Mawile", isMega: false },
  { id: 137, apiName: "medicham", displayName: "Medicham", isMega: false },
  { id: 138, apiName: "meganium", displayName: "Meganium", isMega: false },
  { id: 139, apiName: "meowscarada", displayName: "Meowscarada", isMega: false },
  { id: 140, apiName: "meowstic", displayName: "Meowstic", isMega: false },
  { id: 141, apiName: "meowstic-f", displayName: "Meowstic Female", isMega: false },
  { id: 142, apiName: "metagross", displayName: "Metagross", isMega: false },
  { id: 143, apiName: "milotic", displayName: "Milotic", isMega: false },
  { id: 144, apiName: "mimikyu", displayName: "Mimikyu", isMega: false },
  { id: 145, apiName: "morpeko", displayName: "Morpeko", isMega: false },
  { id: 146, apiName: "rotom-mow", displayName: "Mow Rotom", isMega: false },
  { id: 147, apiName: "mr-mime", displayName: "Mr. Mime", isMega: false },
  { id: 148, apiName: "mr-rime", displayName: "Mr. Rime", isMega: false },
  { id: 149, apiName: "mudsdale", displayName: "Mudsdale", isMega: false },
  { id: 150, apiName: "musharna", displayName: "Musharna", isMega: false },
  { id: 151, apiName: "ninetales", displayName: "Ninetales", isMega: false },
  { id: 152, apiName: "ninetales-alola", displayName: "Ninetales Alolan Form", isMega: false },
  { id: 153, apiName: "noivern", displayName: "Noivern", isMega: false },
  { id: 154, apiName: "oranguru", displayName: "Oranguru", isMega: false },
  { id: 155, apiName: "orthworm", displayName: "Orthworm", isMega: false },
  { id: 156, apiName: "overqwil", displayName: "Overqwil", isMega: false },
  { id: 157, apiName: "palafin", displayName: "Palafin", isMega: false },
  { id: 158, apiName: "pangoro", displayName: "Pangoro", isMega: false },
  { id: 159, apiName: "passimian", displayName: "Passimian", isMega: false },
  { id: 160, apiName: "pawmot", displayName: "Pawmot", isMega: false },
  { id: 161, apiName: "pelipper", displayName: "Pelipper", isMega: false },
  { id: 162, apiName: "perrserker", displayName: "Perrserker", isMega: false },
  { id: 163, apiName: "persian", displayName: "Persian", isMega: false },
  { id: 164, apiName: "pidgeot", displayName: "Pidgeot", isMega: false },
  { id: 165, apiName: "pikachu", displayName: "Pikachu", isMega: false },
  { id: 166, apiName: "pincurchin", displayName: "Pincurchin", isMega: false },
  { id: 167, apiName: "pinsir", displayName: "Pinsir", isMega: false },
  { id: 168, apiName: "politoed", displayName: "Politoed", isMega: false },
  { id: 169, apiName: "polteageist", displayName: "Polteageist", isMega: false },
  { id: 170, apiName: "primarina", displayName: "Primarina", isMega: false },
  { id: 171, apiName: "pyroar", displayName: "Pyroar", isMega: false },
  { id: 172, apiName: "quaquaval", displayName: "Quaquaval", isMega: false },
  { id: 173, apiName: "qwilfish", displayName: "Qwilfish", isMega: false },
  { id: 174, apiName: "raichu", displayName: "Raichu", isMega: false },
  { id: 175, apiName: "raichu-alola", displayName: "Raichu Alolan Form", isMega: false },
  { id: 176, apiName: "rampardos", displayName: "Rampardos", isMega: false },
  { id: 177, apiName: "reuniclus", displayName: "Reuniclus", isMega: false },
  { id: 178, apiName: "rhyperior", displayName: "Rhyperior", isMega: false },
  { id: 179, apiName: "rillaboom", displayName: "Rillaboom", isMega: false },
  { id: 180, apiName: "roserade", displayName: "Roserade", isMega: false },
  { id: 181, apiName: "rotom", displayName: "Rotom", isMega: false },
  { id: 182, apiName: "runerigus", displayName: "Runerigus", isMega: false },
  { id: 183, apiName: "sableye", displayName: "Sableye", isMega: false },
  { id: 184, apiName: "salamence", displayName: "Salamence", isMega: false },
  { id: 185, apiName: "salazzle", displayName: "Salazzle", isMega: false },
  { id: 186, apiName: "samurott", displayName: "Samurott", isMega: false },
  { id: 187, apiName: "samurott-hisui", displayName: "Samurott Hisuian Form", isMega: false },
  { id: 188, apiName: "sandaconda", displayName: "Sandaconda", isMega: false },
  { id: 189, apiName: "sceptile", displayName: "Sceptile", isMega: false },
  { id: 190, apiName: "scizor", displayName: "Scizor", isMega: false },
  { id: 191, apiName: "scolipede", displayName: "Scolipede", isMega: false },
  { id: 192, apiName: "scovillain", displayName: "Scovillain", isMega: false },
  { id: 193, apiName: "scrafty", displayName: "Scrafty", isMega: false },
  { id: 194, apiName: "serperior", displayName: "Serperior", isMega: false },
  { id: 195, apiName: "sharpedo", displayName: "Sharpedo", isMega: false },
  { id: 196, apiName: "simipour", displayName: "Simipour", isMega: false },
  { id: 197, apiName: "simisage", displayName: "Simisage", isMega: false },
  { id: 198, apiName: "simisear", displayName: "Simisear", isMega: false },
  { id: 199, apiName: "sinistcha", displayName: "Sinistcha", isMega: false },
  { id: 200, apiName: "sirfetchd", displayName: "Sirfetch'd", isMega: false },
  { id: 201, apiName: "skarmory", displayName: "Skarmory", isMega: false },
  { id: 202, apiName: "skeledirge", displayName: "Skeledirge", isMega: false },
  { id: 203, apiName: "slowbro", displayName: "Slowbro", isMega: false },
  { id: 204, apiName: "slowbro-galar", displayName: "Slowbro Galarian Form", isMega: false },
  { id: 205, apiName: "slowking", displayName: "Slowking", isMega: false },
  { id: 206, apiName: "slowking-galar", displayName: "Slowking Galarian Form", isMega: false },
  { id: 207, apiName: "slurpuff", displayName: "Slurpuff", isMega: false },
  { id: 208, apiName: "sneasler", displayName: "Sneasler", isMega: false },
  { id: 209, apiName: "snorlax", displayName: "Snorlax", isMega: false },
  { id: 210, apiName: "spiritomb", displayName: "Spiritomb", isMega: false },
  { id: 211, apiName: "squawkabilly", displayName: "Squawkabilly", isMega: false },
  { id: 212, apiName: "staraptor", displayName: "Staraptor", isMega: false },
  { id: 213, apiName: "starmie", displayName: "Starmie", isMega: false },
  { id: 214, apiName: "steelix", displayName: "Steelix", isMega: false },
  { id: 215, apiName: "stunfisk", displayName: "Stunfisk", isMega: false },
  { id: 216, apiName: "swalot", displayName: "Swalot", isMega: false },
  { id: 217, apiName: "swampert", displayName: "Swampert", isMega: false },
  { id: 218, apiName: "sylveon", displayName: "Sylveon", isMega: false },
  { id: 219, apiName: "talonflame", displayName: "Talonflame", isMega: false },
  { id: 220, apiName: "tauros", displayName: "Tauros", isMega: false },
  { id: 221, apiName: "tauros-paldea-aqua-breed", displayName: "Tauros Paldean Form (Aqua Breed)", isMega: false },
  { id: 222, apiName: "tauros-paldea-blaze-breed", displayName: "Tauros Paldean Form (Blaze Breed)", isMega: false },
  { id: 223, apiName: "tauros-paldea-combat-breed", displayName: "Tauros Paldean Form (Combat Breed)", isMega: false },
  { id: 224, apiName: "thievul", displayName: "Thievul", isMega: false },
  { id: 225, apiName: "tinkaton", displayName: "Tinkaton", isMega: false },
  { id: 226, apiName: "torkoal", displayName: "Torkoal", isMega: false },
  { id: 227, apiName: "torterra", displayName: "Torterra", isMega: false },
  { id: 228, apiName: "toucannon", displayName: "Toucannon", isMega: false },
  { id: 229, apiName: "toxapex", displayName: "Toxapex", isMega: false },
  { id: 230, apiName: "toxicroak", displayName: "Toxicroak", isMega: false },
  { id: 231, apiName: "toxtricity", displayName: "Toxtricity", isMega: false },
  { id: 232, apiName: "trevenant", displayName: "Trevenant", isMega: false },
  { id: 233, apiName: "tsareena", displayName: "Tsareena", isMega: false },
  { id: 234, apiName: "typhlosion", displayName: "Typhlosion", isMega: false },
  { id: 235, apiName: "tyranitar", displayName: "Tyranitar", isMega: false },
  { id: 236, apiName: "tyrantrum", displayName: "Tyrantrum", isMega: false },
  { id: 237, apiName: "umbreon", displayName: "Umbreon", isMega: false },
  { id: 238, apiName: "vanilluxe", displayName: "Vanilluxe", isMega: false },
  { id: 239, apiName: "vaporeon", displayName: "Vaporeon", isMega: false },
  { id: 240, apiName: "venusaur", displayName: "Venusaur", isMega: false },
  { id: 241, apiName: "victreebel", displayName: "Victreebel", isMega: false },
  { id: 242, apiName: "vileplume", displayName: "Vileplume", isMega: false },
  { id: 243, apiName: "vivillon", displayName: "Vivillon", isMega: false },
  { id: 244, apiName: "volcarona", displayName: "Volcarona", isMega: false },
  { id: 245, apiName: "rotom-wash", displayName: "Wash Rotom", isMega: false },
  { id: 246, apiName: "watchog", displayName: "Watchog", isMega: false },
  { id: 247, apiName: "weavile", displayName: "Weavile", isMega: false },
  { id: 248, apiName: "whimsicott", displayName: "Whimsicott", isMega: false },
  { id: 249, apiName: "wigglytuff", displayName: "Wigglytuff", isMega: false },
  { id: 250, apiName: "wyrdeer", displayName: "Wyrdeer", isMega: false },
  { id: 251, apiName: "zoroark", displayName: "Zoroark", isMega: false },
  { id: 252, apiName: "mega-abomasnow", displayName: "Mega Abomasnow", isMega: true },
  { id: 253, apiName: "mega-absol", displayName: "Mega Absol", isMega: true },
  { id: 254, apiName: "mega-absol-z", displayName: "Mega Absol Z", isMega: true },
  { id: 255, apiName: "mega-aerodactyl", displayName: "Mega Aerodactyl", isMega: true },
  { id: 256, apiName: "mega-aggron", displayName: "Mega Aggron", isMega: true },
  { id: 257, apiName: "mega-alakazam", displayName: "Mega Alakazam", isMega: true },
  { id: 258, apiName: "mega-altaria", displayName: "Mega Altaria", isMega: true },
  { id: 259, apiName: "mega-ampharos", displayName: "Mega Ampharos", isMega: true },
  { id: 260, apiName: "mega-audino", displayName: "Mega Audino", isMega: true },
  { id: 261, apiName: "mega-banette", displayName: "Mega Banette", isMega: true },
  { id: 262, apiName: "mega-barbaracle", displayName: "Mega Barbaracle", isMega: true },
  { id: 263, apiName: "mega-baxcalibur", displayName: "Mega Baxcalibur", isMega: true },
  { id: 264, apiName: "mega-beedrill", displayName: "Mega Beedrill", isMega: true },
  { id: 265, apiName: "mega-blastoise", displayName: "Mega Blastoise", isMega: true },
  { id: 266, apiName: "mega-blaziken", displayName: "Mega Blaziken", isMega: true },
  { id: 267, apiName: "mega-camerupt", displayName: "Mega Camerupt", isMega: true },
  { id: 268, apiName: "mega-chandelure", displayName: "Mega Chandelure", isMega: true },
  { id: 269, apiName: "mega-charizard-x", displayName: "Mega Charizard X", isMega: true },
  { id: 270, apiName: "mega-charizard-y", displayName: "Mega Charizard Y", isMega: true },
  { id: 271, apiName: "mega-chesnaught", displayName: "Mega Chesnaught", isMega: true },
  { id: 272, apiName: "mega-chimecho", displayName: "Mega Chimecho", isMega: true },
  { id: 273, apiName: "mega-clefable", displayName: "Mega Clefable", isMega: true },
  { id: 274, apiName: "mega-crabominable", displayName: "Mega Crabominable", isMega: true },
  { id: 275, apiName: "mega-delphox", displayName: "Mega Delphox", isMega: true },
  { id: 276, apiName: "mega-dragalge", displayName: "Mega Dragalge", isMega: true },
  { id: 277, apiName: "mega-dragonite", displayName: "Mega Dragonite", isMega: true },
  { id: 278, apiName: "mega-drampa", displayName: "Mega Drampa", isMega: true },
  { id: 279, apiName: "mega-eelektross", displayName: "Mega Eelektross", isMega: true },
  { id: 280, apiName: "mega-emboar", displayName: "Mega Emboar", isMega: true },
  { id: 281, apiName: "mega-excadrill", displayName: "Mega Excadrill", isMega: true },
  { id: 282, apiName: "mega-falinks", displayName: "Mega Falinks", isMega: true },
  { id: 283, apiName: "mega-feraligatr", displayName: "Mega Feraligatr", isMega: true },
  { id: 284, apiName: "mega-floette", displayName: "Mega Floette", isMega: true },
  { id: 285, apiName: "mega-froslass", displayName: "Mega Froslass", isMega: true },
  { id: 286, apiName: "mega-gallade", displayName: "Mega Gallade", isMega: true },
  { id: 287, apiName: "mega-garchomp", displayName: "Mega Garchomp", isMega: true },
  { id: 288, apiName: "mega-garchomp-z", displayName: "Mega Garchomp Z", isMega: true },
  { id: 289, apiName: "mega-gardevoir", displayName: "Mega Gardevoir", isMega: true },
  { id: 290, apiName: "mega-gengar", displayName: "Mega Gengar", isMega: true },
  { id: 291, apiName: "mega-glalie", displayName: "Mega Glalie", isMega: true },
  { id: 292, apiName: "mega-glimmora", displayName: "Mega Glimmora", isMega: true },
  { id: 293, apiName: "mega-golisopod", displayName: "Mega Golisopod", isMega: true },
  { id: 294, apiName: "mega-golurk", displayName: "Mega Golurk", isMega: true },
  { id: 295, apiName: "mega-greninja", displayName: "Mega Greninja", isMega: true },
  { id: 296, apiName: "mega-gyarados", displayName: "Mega Gyarados", isMega: true },
  { id: 297, apiName: "mega-hawlucha", displayName: "Mega Hawlucha", isMega: true },
  { id: 298, apiName: "mega-heracross", displayName: "Mega Heracross", isMega: true },
  { id: 299, apiName: "mega-houndoom", displayName: "Mega Houndoom", isMega: true },
  { id: 300, apiName: "mega-kangaskhan", displayName: "Mega Kangaskhan", isMega: true },
  { id: 301, apiName: "mega-lopunny", displayName: "Mega Lopunny", isMega: true },
  { id: 302, apiName: "mega-lucario", displayName: "Mega Lucario", isMega: true },
  { id: 303, apiName: "mega-lucario-z", displayName: "Mega Lucario Z", isMega: true },
  { id: 304, apiName: "mega-malamar", displayName: "Mega Malamar", isMega: true },
  { id: 305, apiName: "mega-manectric", displayName: "Mega Manectric", isMega: true },
  { id: 306, apiName: "mega-mawile", displayName: "Mega Mawile", isMega: true },
  { id: 307, apiName: "mega-medicham", displayName: "Mega Medicham", isMega: true },
  { id: 308, apiName: "mega-meganium", displayName: "Mega Meganium", isMega: true },
  { id: 309, apiName: "mega-meowstic", displayName: "Mega Meowstic", isMega: true },
  { id: 310, apiName: "mega-metagross", displayName: "Mega Metagross", isMega: true },
  { id: 311, apiName: "mega-pidgeot", displayName: "Mega Pidgeot", isMega: true },
  { id: 312, apiName: "mega-pinsir", displayName: "Mega Pinsir", isMega: true },
  { id: 313, apiName: "mega-pyroar", displayName: "Mega Pyroar", isMega: true },
  { id: 314, apiName: "mega-raichu-x", displayName: "Mega Raichu X", isMega: true },
  { id: 315, apiName: "mega-raichu-y", displayName: "Mega Raichu Y", isMega: true },
  { id: 316, apiName: "mega-sableye", displayName: "Mega Sableye", isMega: true },
  { id: 317, apiName: "mega-salamence", displayName: "Mega Salamence", isMega: true },
  { id: 318, apiName: "mega-sceptile", displayName: "Mega Sceptile", isMega: true },
  { id: 319, apiName: "mega-scizor", displayName: "Mega Scizor", isMega: true },
  { id: 320, apiName: "mega-scolipede", displayName: "Mega Scolipede", isMega: true },
  { id: 321, apiName: "mega-scovillain", displayName: "Mega Scovillain", isMega: true },
  { id: 322, apiName: "mega-scrafty", displayName: "Mega Scrafty", isMega: true },
  { id: 323, apiName: "mega-sharpedo", displayName: "Mega Sharpedo", isMega: true },
  { id: 324, apiName: "mega-skarmory", displayName: "Mega Skarmory", isMega: true },
  { id: 325, apiName: "mega-slowbro", displayName: "Mega Slowbro", isMega: true },
  { id: 326, apiName: "mega-staraptor", displayName: "Mega Staraptor", isMega: true },
  { id: 327, apiName: "mega-starmie", displayName: "Mega Starmie", isMega: true },
  { id: 328, apiName: "mega-steelix", displayName: "Mega Steelix", isMega: true },
  { id: 329, apiName: "mega-swampert", displayName: "Mega Swampert", isMega: true },
  { id: 330, apiName: "mega-tyranitar", displayName: "Mega Tyranitar", isMega: true },
  { id: 331, apiName: "mega-venusaur", displayName: "Mega Venusaur", isMega: true },
  { id: 332, apiName: "mega-victreebel", displayName: "Mega Victreebel", isMega: true },
];